### ISSUE TITLE
Active TCP and UDB Connections

### ISSUE THREAD

**Issue by reynonic** [TianYu-00/PalworldServerManager#3]
Just wanted to know what all of these connections are being used for. Are these all SteamCMD on a server instance with no active connections?
![image](https://github.com/TianYu-00/PalworldServerManager/assets/39746322/921d490b-0686-4978-b08a-83d938fc1dfb)
![image](https://github.com/TianYu-00/PalworldServerManager/assets/39746322/5dc2effd-f533-4428-bb97-6527a254cd09)

**Comment by tianyu-00** [comment]
I believe theyre all part of the palworld server connections. Not 100% sure what theyre used for though but by the looks of it, its most likely for multiplayer use.
