### ISSUE TITLE
Since Palworld 2.1.0 update restart feature no longer works

### ISSUE THREAD

**Issue by Onsqa** [TianYu-00/PalworldServerManager#5]
Location of the problem:

https://github.com/TianYu-00/PalworldServerManager/blob/b71f853f332c8a447a546b48f50cec116c50953b/PalworldServerManager/PalworldServerManager/Form1.cs#L445

Since the newest update process name is "PalServer-Win64-Shipping-Cmd"

**Comment by tianyu-00** [comment]
Thanks for reporting the bug! Much appreciated <3

**Comment by tianyu-00** [comment]
Issue is now fixed.

**Comment by Onsqa** [comment]
fix confirmed. Works as intended
