### ISSUE TITLE
Check server CMD crash restart interval restart server everytime

### ISSUE THREAD

**Issue by nruffier** [TianYu-00/PalworldServerManager#6]
Hi,

I've set Check server CMD crash restart interval restart server even if cmd is still running...
Have I missed something ?

Thanks

**Comment by tianyu-00** [comment]
Ahh yes i forgot to change the process name for it since theyve now changed it to `PalServer-Win64-Shipping-Cmd` , ill update it now.

**Comment by tianyu-00** [comment]
Hello, issue is now fixed.

**Comment by nruffier** [comment]
Thanks a lot !

**Comment by tianyu-00** [comment]
no problem at all, thanks for letting me know😄.
