### ISSUE TITLE
New Things

### ISSUE THREAD

**Issue by tuvok81** [TianYu-00/PalworldServerManager#8]
Hello,
a Question .. 
- is this possible to see over the Discord Webhook the Player Join/Part from the Server?
- Auto Update if it gives a new update than post a message on the Server and Discord and Update it with a time cooldown
- different Discord channel for Post the new Version in Discord
- Console Window include in the Programm Window?

is this possibel to update the Tool for that? It was very nice

**Comment by tianyu-00** [comment]
Hello Tuvok18,

Thank you for reaching out and sharing your ideas! Unfortunately, I no longer have enough free time to actively work on this project. However, feel free to fork the project and implement these features.

Best of luck to you.
